export default {
    WORLD_HANDSHAKE: 14,
    WORLD_CONNECT: 16,
    WORLD_RECONNECT: 18,

    JS5_OPEN: 15,

    CREATE_LOG_PROGRESS: 20, // complete guess
    CREATE_CHECK_NAME: 21,
    CREATE_ACCOUNT: 22,

    WORLDLIST_FETCH: 23,
};
